### ISSUE TITLE
Moving towards a server (without GUI / windows manager)

### ISSUE THREAD

**Issue by Xoib** [raphael0202/leboncoin_manager#1]
Hello,

I am currently trying to adapt your code in order to make it work in a headless server (= without GUI or X).

I am not familiar with the possibilities of seleniumhq but for the moment I made this change : 

```
 class LeboncoinManager:
     def __init__(self, username=None, password=None):
-        self.driver = webdriver.Firefox()
+        # Create a copy of desired capabilities object.
+        desired_capabilities = webdriver.DesiredCapabilities.HTMLUNIT.copy()
+        # Change the proxy properties of that copy.
+        desired_capabilities['acceptSslCerts'] = True
+        self.driver = webdriver.Remote("http://www.whateverhere.org", desired_capabilities)
         self.wait = WebDriverWait(self.driver, 10)
```

But it fail with json decoding.

Let me know if you are willing to continue your work in this project.

Thanks,

**Comment by raphael0202** [comment]
Hi,
I've read the doc about DesiredCapabilities, and I'm not sure it can be used to emulate a web browser without GUI. But most of (all?) the requests can be actually done without selenium anyway.
And yes I'm willing to turn this into a headless server using the standard library.
I'm going to create a new brand `dev` to work on it, do not hesitate to submit PR if you want to participate.

**Comment by Xoib** [comment]
Ok great !
